blog-app-ruby-on-rizzies/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :posts do
    resources :comments
  end

  root "posts#index"
  
  get '/about', to: 'pages#about'
end

blog-app-ruby-on-rizzies/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog-app-ruby-on-rizzies/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

blog-app-ruby-on-rizzies/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5}
  validates :body, presence: true
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

blog-app-ruby-on-rizzies/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blog-app-ruby-on-rizzies/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  private

   # Overwriting the sign_out redirect path method
   def after_sign_out_path_for(resource_or_scope)
     new_user_session_path
   end
   
 end

blog-app-ruby-on-rizzies/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

blog-app-ruby-on-rizzies/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

end

blog-app-ruby-on-rizzies/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
    redirect_to @post
  else
    render 'new'
  end
  end

  def show
    @post = Post.find(params[:id])
end

def edit
  @post = Post.find(params[:id])
end

def update
  @post = Post.find(params[:id])

  if @post.update(params[:post].permit(:title, :body))
    redirect_to @post
  else
    render 'edit'
  end
end
def destroy
  @post = Post.find(params[:id])
  @post.destroy

  redirect_to posts_path
end

  private
  def post_params
    params.require(:post).permit(:title, :body, :image)
  end
end

blog-app-ruby-on-rizzies/app/helpers/application_helper.rb
module ApplicationHelper
end

blog-app-ruby-on-rizzies/app/helpers/comments_helper.rb
module CommentsHelper
end

blog-app-ruby-on-rizzies/app/helpers/pages_helper.rb
module PagesHelper
end

blog-app-ruby-on-rizzies/app/helpers/posts_helper.rb
module PostsHelper
end

blog-app-ruby-on-rizzies/app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong> <%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %>Ago</p>

  </div>
<% if user_signed_in? %>
  <p><%= link_to 'Delete', [comment.post, comment],
                  method: :delete,
                  class: "button",
                  data: { confirm: 'Are you sure?' } %>
  </p>
  <% end %>

</div>

blog-app-ruby-on-rizzies/app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
  </p>
    <%= f.submit %>


<% end %>

blog-app-ruby-on-rizzies/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppRubyOnRizzies</title>
    <%= csrf_meta_tags %>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400, 700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <div id="sidebar">
      <div id="logo">
        <%= link_to root_path do %>
        <%= image_tag "tessy.png", :size => '110x110', :class => 'img-responsive' %>

        <% end %>
      </div>
<br>
      <ul>
        <li class="category">Website</li>
        <li><%= link_to "Blog", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <ul>
        <li class="category">Social</li>
        <li><a href="#"> IG </a></li>
        <li><a href="#"> Github</a></li>
        <li><a href="mailto:Lamar5503@me.com"> Email </a></li>
        <li><a href="#"> Facebook </a></li>
      </ul>
      <% if !user_signed_in? %>
      <p class="sign_in">Admin Login</p>
      <% end %>
    </div>
    <div id="main_content">
  		<div id="header">
  			<% if current_page?(root_path) %>
  				<p>All Posts</p>
  			<% elsif current_page?(about_path) %>
  				<p>About</p>
  			<% else %>
  				<%= link_to "Back to All Posts", root_path %>
  			<% end %>

        <% if user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "New Post", new_post_path %> 	&nbsp; <i class="fa fa-plus" aria-hidden="true"></i></button>
          <button class="button" >  <%= link_to 'Logout', destroy_user_session_path, :method => :delete, data: {:confirm=>'Are you sure?'} %>     </button>
        </div>
        <% else %>
  				<%= link_to "Sign in", new_user_session_path %>
        <% end %>
      </div>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
        <% end %>
          <%= yield %>
    </div>

  </body>
</html>

blog-app-ruby-on-rizzies/app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
    <%= image_tag "Untitled-1.png" %>
  </div>
  <div id="content">
  <h2>Whats good, I'm Lamar Smith</h2>
    <p>Welcome to my personal blog I built in Rails 4</p>
    <p>I am currently working on a React on Rails app for my final project</p>
  <p>I will be going on my 9th of 12 weeks at General Assembly in San Francisco, CA.</p>
  <p>
  "Feel free to drop a comment until we get the like feature working"</p>

  </div>
</div>

blog-app-ruby-on-rizzies/app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
<% if @post.errors.any? %>
<div id="errors">
  <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>

    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</div>

<div class="field">
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :body %><br>
  <%= f.text_area :body %>
</div>

<div class="actions">
  <%= f.submit%>
</div>
<% end %>

blog-app-ruby-on-rizzies/app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit a post</h1>
   <%= render 'form' %>
</div>

blog-app-ruby-on-rizzies/app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post_wrapper">
  <%= image_tag post.image.url(:medium) %>
  <h2 class="title"><%= link_to post.title, post %></h2>
  <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
</div>
<% end %>

blog-app-ruby-on-rizzies/app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>Write a post</h1>
   <%= render 'form' %>
</div>

blog-app-ruby-on-rizzies/app/views/posts/show.html.erb
<div id="post_content">
  <%= image_tag @post.image.url(:medium) %>
  <h1 class="title"><%= @post.title %></h1>
  <p class="date">
    Submitted
    <%= time_ago_in_words(@post.created_at) %>
    Ago |
    <% if user_signed_in? %>
    <%= link_to 'Edit', edit_post_path(@post) %>
    |
    <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <p class="body"><%= @post.body %></p>

  <div id="comments">
    <h2><%= @post.comments.count %>
      Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment:</h3>
    <%= render "comments/form" %>
  </div>
</div>